#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : JAGS
Version  : 4.3.0
Release  : 1
URL      : https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Source/JAGS-4.3.0.tar.gz
Source0  : https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Source/JAGS-4.3.0.tar.gz
Summary  : Bayesian hierarchical models using Markov Chain Monte Carlo (MCMC) simulation
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: JAGS-bin = %{version}-%{release}
Requires: JAGS-lib = %{version}-%{release}
Requires: JAGS-libexec = %{version}-%{release}
Requires: JAGS-license = %{version}-%{release}
Requires: JAGS-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex
BuildRequires : gfortran
BuildRequires : openblas-dev
BuildRequires : pkgconfig(cppunit)

%description
This is GNU libltdl, a system independent dlopen wrapper for GNU libtool.
It supports the following dlopen interfaces:
* dlopen (POSIX)
* shl_load (HP-UX)
* LoadLibrary (Win16 and Win32)
* load_add_on (BeOS)
* GNU DLD (emulates dynamic linking for static libraries)
* dyld (darwin/Mac OS X)
* libtool's dlpreopen
--
Written by Thomas Tanner, 1999

%package bin
Summary: bin components for the JAGS package.
Group: Binaries
Requires: JAGS-libexec = %{version}-%{release}
Requires: JAGS-license = %{version}-%{release}
Requires: JAGS-man = %{version}-%{release}

%description bin
bin components for the JAGS package.


%package dev
Summary: dev components for the JAGS package.
Group: Development
Requires: JAGS-lib = %{version}-%{release}
Requires: JAGS-bin = %{version}-%{release}
Provides: JAGS-devel = %{version}-%{release}
Requires: JAGS = %{version}-%{release}

%description dev
dev components for the JAGS package.


%package lib
Summary: lib components for the JAGS package.
Group: Libraries
Requires: JAGS-libexec = %{version}-%{release}
Requires: JAGS-license = %{version}-%{release}

%description lib
lib components for the JAGS package.


%package libexec
Summary: libexec components for the JAGS package.
Group: Default
Requires: JAGS-license = %{version}-%{release}

%description libexec
libexec components for the JAGS package.


%package license
Summary: license components for the JAGS package.
Group: Default

%description license
license components for the JAGS package.


%package man
Summary: man components for the JAGS package.
Group: Default

%description man
man components for the JAGS package.


%prep
%setup -q -n JAGS-4.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550851588
%configure --disable-static --with-blas=openblas
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1550851588
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/JAGS
cp COPYING %{buildroot}/usr/share/package-licenses/JAGS/COPYING
cp libltdl/COPYING.LIB %{buildroot}/usr/share/package-licenses/JAGS/libltdl_COPYING.LIB
cp src/modules/glm/SSparse/CHOLMOD/Check/License.txt %{buildroot}/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Check_License.txt
cp src/modules/glm/SSparse/CHOLMOD/Cholesky/License.txt %{buildroot}/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Cholesky_License.txt
cp src/modules/glm/SSparse/CHOLMOD/Core/License.txt %{buildroot}/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Core_License.txt
cp src/modules/glm/SSparse/CHOLMOD/MatrixOps/License.txt %{buildroot}/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_MatrixOps_License.txt
cp src/modules/glm/SSparse/CHOLMOD/MatrixOps/gpl.txt %{buildroot}/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_MatrixOps_gpl.txt
cp src/modules/glm/SSparse/CHOLMOD/Modify/License.txt %{buildroot}/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Modify_License.txt
cp src/modules/glm/SSparse/CHOLMOD/Modify/gpl.txt %{buildroot}/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Modify_gpl.txt
cp src/modules/glm/SSparse/CHOLMOD/Supernodal/License.txt %{buildroot}/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Supernodal_License.txt
cp src/modules/glm/SSparse/CHOLMOD/Supernodal/gpl.txt %{buildroot}/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Supernodal_gpl.txt
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jags

%files dev
%defattr(-,root,root,-)
/usr/include/JAGS/Console.h
/usr/include/JAGS/JRmath.h
/usr/include/JAGS/compiler/Compiler.h
/usr/include/JAGS/compiler/Counter.h
/usr/include/JAGS/compiler/CounterTab.h
/usr/include/JAGS/compiler/LogicalFactory.h
/usr/include/JAGS/compiler/MixtureFactory.h
/usr/include/JAGS/compiler/NodeFactory.h
/usr/include/JAGS/compiler/ObsFuncTab.h
/usr/include/JAGS/compiler/ParseTree.h
/usr/include/JAGS/distribution/ArrayDist.h
/usr/include/JAGS/distribution/DistError.h
/usr/include/JAGS/distribution/DistPtr.h
/usr/include/JAGS/distribution/DistTab.h
/usr/include/JAGS/distribution/Distribution.h
/usr/include/JAGS/distribution/RScalarDist.h
/usr/include/JAGS/distribution/ScalarDist.h
/usr/include/JAGS/distribution/VectorDist.h
/usr/include/JAGS/function/ArrayFunction.h
/usr/include/JAGS/function/ArrayLogDensity.h
/usr/include/JAGS/function/DFunction.h
/usr/include/JAGS/function/DPQFunction.h
/usr/include/JAGS/function/FuncError.h
/usr/include/JAGS/function/FuncTab.h
/usr/include/JAGS/function/Function.h
/usr/include/JAGS/function/FunctionPtr.h
/usr/include/JAGS/function/LinkFunction.h
/usr/include/JAGS/function/PFunction.h
/usr/include/JAGS/function/QFunction.h
/usr/include/JAGS/function/ScalarFunction.h
/usr/include/JAGS/function/ScalarLogDensity.h
/usr/include/JAGS/function/ScalarVectorFunction.h
/usr/include/JAGS/function/VectorFunction.h
/usr/include/JAGS/function/VectorLogDensity.h
/usr/include/JAGS/graph/AggNode.h
/usr/include/JAGS/graph/ArrayLogicalNode.h
/usr/include/JAGS/graph/ArrayStochasticNode.h
/usr/include/JAGS/graph/ConstantNode.h
/usr/include/JAGS/graph/DeterministicNode.h
/usr/include/JAGS/graph/Graph.h
/usr/include/JAGS/graph/GraphMarks.h
/usr/include/JAGS/graph/LinkNode.h
/usr/include/JAGS/graph/LogicalNode.h
/usr/include/JAGS/graph/MixTab.h
/usr/include/JAGS/graph/MixtureNode.h
/usr/include/JAGS/graph/Node.h
/usr/include/JAGS/graph/NodeError.h
/usr/include/JAGS/graph/ParentError.h
/usr/include/JAGS/graph/ScalarLogicalNode.h
/usr/include/JAGS/graph/ScalarStochasticNode.h
/usr/include/JAGS/graph/StochasticNode.h
/usr/include/JAGS/graph/VSLogicalNode.h
/usr/include/JAGS/graph/VectorLogicalNode.h
/usr/include/JAGS/graph/VectorStochasticNode.h
/usr/include/JAGS/model/BUGSModel.h
/usr/include/JAGS/model/Model.h
/usr/include/JAGS/model/Monitor.h
/usr/include/JAGS/model/MonitorControl.h
/usr/include/JAGS/model/MonitorFactory.h
/usr/include/JAGS/model/MonitorInfo.h
/usr/include/JAGS/model/NodeArray.h
/usr/include/JAGS/model/NodeArraySubset.h
/usr/include/JAGS/model/SymTab.h
/usr/include/JAGS/module/Module.h
/usr/include/JAGS/module/ModuleError.h
/usr/include/JAGS/rng/RNG.h
/usr/include/JAGS/rng/RNGFactory.h
/usr/include/JAGS/rng/RmathRNG.h
/usr/include/JAGS/rng/TruncatedNormal.h
/usr/include/JAGS/sampler/GraphView.h
/usr/include/JAGS/sampler/ImmutableSampleMethod.h
/usr/include/JAGS/sampler/ImmutableSampler.h
/usr/include/JAGS/sampler/Linear.h
/usr/include/JAGS/sampler/Metropolis.h
/usr/include/JAGS/sampler/MutableSampleMethod.h
/usr/include/JAGS/sampler/MutableSampler.h
/usr/include/JAGS/sampler/RWMetropolis.h
/usr/include/JAGS/sampler/SampleMethodNoAdapt.h
/usr/include/JAGS/sampler/Sampler.h
/usr/include/JAGS/sampler/SamplerFactory.h
/usr/include/JAGS/sampler/SingletonFactory.h
/usr/include/JAGS/sampler/SingletonGraphView.h
/usr/include/JAGS/sampler/Slicer.h
/usr/include/JAGS/sampler/StepAdapter.h
/usr/include/JAGS/sampler/TemperedMetropolis.h
/usr/include/JAGS/sarray/Range.h
/usr/include/JAGS/sarray/RangeIterator.h
/usr/include/JAGS/sarray/SArray.h
/usr/include/JAGS/sarray/SimpleRange.h
/usr/include/JAGS/util/dim.h
/usr/include/JAGS/util/integer.h
/usr/include/JAGS/util/logical.h
/usr/include/JAGS/util/nainf.h
/usr/include/JAGS/version.h
/usr/lib64/libjags.so
/usr/lib64/libjrmath.so
/usr/lib64/pkgconfig/jags.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/JAGS/modules-4/basemod.so
/usr/lib64/JAGS/modules-4/bugs.so
/usr/lib64/JAGS/modules-4/dic.so
/usr/lib64/JAGS/modules-4/glm.so
/usr/lib64/JAGS/modules-4/lecuyer.so
/usr/lib64/JAGS/modules-4/mix.so
/usr/lib64/JAGS/modules-4/msm.so
/usr/lib64/libjags.so.4
/usr/lib64/libjags.so.4.0.3
/usr/lib64/libjrmath.so.0
/usr/lib64/libjrmath.so.0.0.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/jags-terminal

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/JAGS/COPYING
/usr/share/package-licenses/JAGS/libltdl_COPYING.LIB
/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Check_License.txt
/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Cholesky_License.txt
/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Core_License.txt
/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_MatrixOps_License.txt
/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_MatrixOps_gpl.txt
/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Modify_License.txt
/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Modify_gpl.txt
/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Supernodal_License.txt
/usr/share/package-licenses/JAGS/src_modules_glm_SSparse_CHOLMOD_Supernodal_gpl.txt

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/jags.1
